### ISSUE TITLE
[Python3] Error of MIDI file open when no settings was presented

### ISSUE THREAD

**Issue by Wohlstand** [adambiser/imf-creator#11]
I have suddenly found that the `self.settings.song_file.get()` for the case when first time use, returns the string "None", but not the python `None` type. In result an error that "File or directory None is not exist".

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/wohlstand/_git_repos/imf-creator/imfcreator/__main__.py", line 323, in <lambda>
    self.settings.song_file.trace_add("write", lambda *_: self.reload_midi_song())
  File "/home/wohlstand/_git_repos/imf-creator/imfcreator/__main__.py", line 382, in reload_midi_song
    self._midi_song = MidiSongFile.load_file(self.settings.song_file.get())
  File "/home/wohlstand/_git_repos/imf-creator/imfcreator/plugins/__init__.py", line 229, in load_file
    with open(filename, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'None'
```

**Comment by adambiser** [comment]
Should be fixed.  It won't fix any settings that are already set to "None" though.
